### ISSUE TITLE
Exception in delivering result of invoking 'froatsnook:shopify/HandleAuthRedirect'

### ISSUE THREAD

**Issue by afang** [froatsnook/meteor-shopify#13]
I am getting an error when calling `api.getUsers`:
```
var authenticator = new Shopify.PublicAppOAuthAuthenticator({
			shop: e.target.storeName.value,
			api_key: "",
			keyset: "default",
			scopes: "all",

			onAuth: function(accessToken) {
				console.log(accessToken);
				var api = new Shopify.API({authenticator: authenticator});
				console.log(api.getUsers());
				Meteor.call('user/create', accessToken)
			}
		});

```

```Exception in delivering result of invoking 'froatsnook:shopify/HandleAuthRedirect': Error: Match error: Match error: Expected string, got undefined```

**Comment by afang** [comment]
I tried calling `api.getUsers()` from the server and got this error:

```

I20160103-17:33:02.334(-5)? Exception while invoking method 'user/create' Error: failed [501] {"errors":"[API] That action is not currently supported."}

I20160103-17:33:02.335(-5)?     at Object.Future.wait (/Users/andyfang/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)

I20160103-17:33:02.335(-5)?     at ShopifyAPI.getUsers (packages/meteor/helpers.js:119:1)

I20160103-17:33:02.335(-5)?     at [object Object].Meteor.methods.user/create (server/methods.js:11:19)

I20160103-17:33:02.335(-5)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)

I20160103-17:33:02.335(-5)?     at livedata_server.js:708:19

I20160103-17:33:02.336(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)

I20160103-17:33:02.336(-5)?     at livedata_server.js:706:40

I20160103-17:33:02.336(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)

I20160103-17:33:02.336(-5)?     at livedata_server.js:704:46

I20160103-17:33:02.336(-5)?     at tryCallTwo (/Users/andyfang/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)

I20160103-17:33:02.336(-5)?     - - - - -

I20160103-17:33:02.336(-5)?     at makeErrorByStatus (packages/http/httpcall_common.js:16:1)

I20160103-17:33:02.336(-5)?     at Request._callback (packages/http/httpcall_server.js:113:1)

I20160103-17:33:02.336(-5)?     at Request.self.callback (/Users/andyfang/.meteor/packages/http/.1.1.1.rwvb9p++os+web.browser+web.cordova/npm/node_modules/request/request.js:344:22)

I20160103-17:33:02.336(-5)?     at Request.emit (events.js:98:17)

I20160103-17:33:02.336(-5)?     at Request.<anonymous> (/Users/andyfang/.meteor/packages/http/.1.1.1.rwvb9p++os+web.browser+web.cordova/npm/node_modules/request/request.js:1239:14)

I20160103-17:33:02.336(-5)?     at Request.emit (events.js:117:20)

I20160103-17:33:02.337(-5)?     at IncomingMessage.<anonymous> (/Users/andyfang/.meteor/packages/http/.1.1.1.rwvb9p++os+web.browser+web.cordova/npm/node_modules/request/request.js:1187:12)

I20160103-17:33:02.337(-5)?     at IncomingMessage.emit (events.js:117:20)

I20160103-17:33:02.337(-5)?     at _stream_readable.js:944:16

I20160103-17:33:02.337(-5)?     at process._tickCallback (node.js:448:13)
```

code:
```
'user/create': function (accessToken) {
		var api = new Shopify.API({
			shop: 'andys-shirts',
			access_token: accessToken
		});
		console.log(api.getUsers());
}

**Comment by froatsnook** [comment]
OK for your first issue:

1. Have you filled in the `api_key`?
2. How do you define the "default" keyset?
3. Are you sure that the shop name is correct?  It should have a value like "test-store" if your store can be accessed at "test-store.myshopify.com".
4. I'm not sure if creating the Shopify.API using that authenticator will work.  I think if you haven't called `Shopify.harden`, then it might.  But it's probably a bad idea to expose the accessToken on the client.  I think this is part of the API is very confusing, but following the basic example will point you in the right direction.  Do something like this:

```javascript
// server
Shopify.addKeyset("default", {
    api_key: "Your API key",
    secret: "Your secret",
});

Shopify.harden(); // you don't want accessToken exposed to client
Shopify.onAuth(function(accessToken, authConfig) {
    var shop = authConfig.shop;
    Shopify.addKeyset(shop, {
        access_token: accessToken
    });

    // do this server-side since that's where we have the accessToken
    Meteor.call('user/create', accessToken);
});

// client
var authenticator = new Shopify.PublicAppOAuthAuthenticator({
    shop: e.target.storeName.value,
    api_key: "...",
    keyset: "default",
    scopes: "all",

    onAuth: function() { // no accessToken
        // use the keyset created above for this user's shop
        var api = new Shopify.API({ keyset: e.target.storeName.value  });
        console.log(api.getUsers());
    }
});
```

Basically, the "default" keyset is used for auth, and each shop gets its own keyset.  To make this secure, use a uuid instead of the shop name as the keyset name.  I don't understand everything that's going on in your case, but if I were you I would probably do something like this:

1. Make an object called `auths` in the server.  It should have shop as the key and access token as the value.
2. Call `Accounts.createUser` in the client-side onAuth.  Provide `e.target.storeName.value` as `shop` in the profile.
3. In the server-side `Accounts.onCreateUser`, do this:

```javascript
Accounts.onCreateUser(function(options, user) {
    user.profile = options.profile;
    var accessToken = auths[options.profile.shop];
    user.accessToken = accessToken; // not published
    delete auths[options.profile.shop];
    var keysetName = Meteor.uuid();
    user.profile.keyset = keysetName; // published because in profile
    Shopify.addKeyset(keysetName, {
        access_token: accessToken,
    });
    return user;
});
```

I think the right way to do this would have been to make an `accounts-shopify` just like `accounts-meetup` or `accounts-facebook`.  Maybe in 2.0 :).

**Comment by froatsnook** [comment]
As for your second comment, according to [Shopify docs](https://docs.shopify.com/api/user),

> The User resource is currently only available to Shopify Plus Customers.

Are you a Shopify Plus customer?

**Comment by afang** [comment]
Ah I see, I'm not a Shopify Plus customer. I'm only using the User resource to get the email/ name of the Shopify owner. I guess that's not what this API is intended for.

**Comment by afang** [comment]
Never mind I'm still having the issue. The app I'm building doesn't use Accounts, so I will need to make the `accessToken` available to the client (currently in Sessions).

```
	'submit form.authentication': function(e) {
		e.preventDefault()

		var authenticator = new Shopify.PublicAppOAuthAuthenticator({
			shop: e.target.storeName.value,
			api_key: '...',
			keyset: 'default',
			scopes: 'all',

			onAuth: function() {
			var api = new Shopify.API({
				shop: e.target.storeName.value,
				keyset:'default'
			});
			// tried this also:
			// var api = new Shopify.API({
			// 	authenticator: authenticator
			// });
			console.log(api.countOrders());
		}
	});
		authenticator.openAuthTab();
	}
```

**Comment by froatsnook** [comment]
You don't need to expose the access token to the client even if you don't use accounts.  I assume you don't mind making the user re-auth after the server reboots?  Just call `Shopify.addKeyset` and it will last until the server reboots.

Here's a quick solution:

```javascript
// server

// Meteor method to make a name for the keyset given a shop.
var keysetNames = { }; // shop => uuid
Meteor.methods({
    GenKeysetName: function(shop) {
        var uuid = Meteor.uuid();
        keysetNames[shop] = uuid;
        return uuid;
    },
});

// Make the keyset on auth
Shopify.onAuth(function(accessToken, authConfig) {
    // Make a keyset with this access token for the given shop
    var keysetName = keysetNames[authConfig.shop];
    Shopify.addKeyset(keysetName, {
        access_token: accessToken
    });
});
```

```javascript
// client

// First make a keyset name by calling the meteor method
Meteor.call("GenKeysetName", e.target.storeName.value, function(err, keyset) {
    // now both client and server know that the keyset's name will be `keyset`

    var authenticator = new Shopify.PublicAppOAuthAuthenticator({
        shop: e.target.storeName.value,
        api_key: "...",
        keyset: "default",
        scopes: "all",

        onAuth: function() {
            // Use the keyset name we got from the meteor method
            var api = new Shopify.API({ keyset: keyset  });
            console.log(api.getUsers());
        }
    });

    authenticator.openAuthTab();
});
```

**Comment by froatsnook** [comment]
The reason that your example isn't working is that the default keyset (I assume you create this using your api key and secret) only works for auth.  The proper solution is to make a new keyset after each authentication.

If you just want the simple (insecure) solution, you can just pass the `access_token` directly to the new Shopify.API, but then you'll need to specify `insecure: true` as an option.

```javascript
onAuth: function(accessToken) {
    var api = new Shopify.API({
        shop: e.target.storeName.value,
        access_token: accessToken
    });
},
```

**Comment by dbnoble** [comment]
If you want to persist the keysets between reloads, you can write a serverside method to add the new keyset and also save it to a collection in the DB, then reintroduce each keyset on server startup.

For example, in /server/ place a file with:
```
Meteor.startup(function () {
  existingKeysets = Keysets.find({});
  existingKeysets.forEach(function(keyset) {
    var thisShopUUID = keyset.shop;
    var thisToken = keyset.token;
     Shopify.addKeyset(thisShopUUID, {
     access_token: thisToken
     });
  });
}
```

There may be a better way to do this, but it works for me.

**Comment by froatsnook** [comment]
@dbnoble: :+1:

**Comment by froatsnook** [comment]
Feel free to re-open or open another issue.
